//
// Created by Kevin Qiao on 3/28/2023.
//

#ifndef AQUA_CPP_BASELINEREMOVEANDNOISEESTIMATION_H
#define AQUA_CPP_BASELINEREMOVEANDNOISEESTIMATION_H

#include "../data/data.h"


namespace AQuA{


}// namespace

#endif //AQUA_CPP_BASELINEREMOVEANDNOISEESTIMATION_H
